apiVersion: v1
kind: Service
metadata:
  name: doriscluster-sample-be-service
  namespace: doris
  labels:
    app.doris.ownerreference/name: doriscluster-sample
    app.doris.service/role: access
    app.kubernetes.io/component: be
  annotations:
    app.doris.components/hash: "142869532"
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  selector:
    app.doris.ownerreference/name: doriscluster-sample-be
    app.kubernetes.io/component: be
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  clusterIP: 10.0.9.80
  ports:
  - name: be-port
    port: 9060
    targetPort: 9060
    protocol: TCP
  - name: webserver-port
    port: 8040
    targetPort: 8040
    protocol: TCP
  - name: heartbeat-port
    port: 9050
    targetPort: 9050
    protocol: TCP
  - name: brpc-port
    port: 8060
    targetPort: 8060
    protocol: TCP
