# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.doris.components/hash: "2820608763"
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-07-11T08:47:56Z"
  labels:
    app.doris.ownerreference/name: doriscluster-sample
    app.doris.service/role: access
    app.kubernetes.io/component: be
  name: doriscluster-sample-be-service
  namespace: doris
  ownerReferences:
  - apiVersion: doris.selectdb.com/v1
    kind: DorisCluster
    name: doriscluster-sample
    uid: 59c0a316-5d16-449f-b3a4-d3edda6cdecd
  resourceVersion: "247496830"
  uid: 1e9a3f16-eece-4ad9-86c7-1ccf8166a071
spec:
  clusterIP: 10.0.13.155
  clusterIPs:
  - 10.0.13.155
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: be-port
    port: 9060
    protocol: TCP
    targetPort: 9060
  - name: webserver-port
    port: 8040
    protocol: TCP
    targetPort: 8040
  - name: heartbeat-port
    port: 9050
    protocol: TCP
    targetPort: 9050
  - name: brpc-port
    port: 8060
    protocol: TCP
    targetPort: 8060
  selector:
    app.doris.ownerreference/name: doriscluster-sample-be
    app.kubernetes.io/component: be
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
