apiVersion: v1
kind: PersistentVolume
metadata:
 name: bold-dorisfe-fileserver
 namespace: doris
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 nfs:
   path: /filestore/DorisFe
   server: 10.109.160.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: bold-dorisfe-fileserver-claim
 namespace: doris
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: bold-dorisfe-fileserver
 resources:
   requests:
     storage: 3Gi