# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    app.doris.components/hash: "2613611586"
  generation: 1
  labels:
    app.doris.ownerreference/name: doriscluster-sample
    app.kubernetes.io/component: fe
  name: doriscluster-sample-fe
  namespace: doris
  ownerReferences:
  - apiVersion: doris.selectdb.com/v1
    kind: DorisCluster
    name: doriscluster-sample
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.doris.ownerreference/name: doriscluster-sample-fe
      app.kubernetes.io/component: fe
  serviceName: doriscluster-sample-fe-internal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.doris.cluster: doriscluster-sample
        app.doris.ownerreference/name: doriscluster-sample-fe
        app.kubernetes.io/component: fe
      name: doriscluster-sample-fe
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - fe
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - args:
        - $(ENV_FE_ADDR)
        command:
        - /opt/apache-doris/fe_entrypoint.sh
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONFIGMAP_MOUNT_PATH
          value: /etc/doris
        - name: USER
          value: root
        - name: DORIS_ROOT
          value: /opt/apache-doris
        - name: ENV_FE_ADDR
          value: doriscluster-sample-fe-service
        - name: FE_QUERY_PORT
          value: "9030"
        - name: ELECT_NUMBER
          value: "3"
        image: selectdb/doris.fe-ubuntu:2.1.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/apache-doris/fe_prestop.sh
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 80
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9030
          timeoutSeconds: 180
        name: fe
        ports:
        - containerPort: 8030
          name: http-port
          protocol: TCP
        - containerPort: 9020
          name: rpc-port
          protocol: TCP
        - containerPort: 9030
          name: query-port
          protocol: TCP
        - containerPort: 9010
          name: edit-log-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 8030
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "3"
            memory: 8Gi
          requests:
            cpu: "3"
            memory: 8Gi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9030
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
        - mountPath: /opt/apache-doris/fe/doris-meta
          name: fe-meta
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: fe-meta
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: doriscluster-sample-fe-5b5446b989
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: doriscluster-sample-fe-5b5446b989
  updatedReplicas: 1
